### PR TITLE
Add dev instructions for editing spec website

### PR DESCRIPTION
**Pull request by Shrinks99**
It's not particularly complicated but _I_ didn't know what was required for ReSpec and had to google for 5 minutes so why not save everyone else that trouble eh? :)

### CODE REVIEW

**Review by ikreymer — APPROVED** [review]

**Comment by edsu** [comment]
I think you should be able to open the file directly using your browser too?

**Comment by Shrinks99** [comment]
@edsu Was just looking at this actually!  I don't think my instructions are accurate anymore and we'd need some sort of on-the-fly conversion (like Jekyll does) in order to make this happen once all the other files are in Markdown.  Any suggestions / recommendations?

**Comment by edsu** [comment]
Hmm, good point. I was using a test repo to run the action, but that's not very convenient.

I think I could make `markdown_to_respec` pip installable, so could run from the command line, if you have Python installed. Would that be helpful?

**Comment by Shrinks99** [comment]
That might be a good first step?  Then we could create a simple development build script that would run `http.server` in the directory, watch for changes, and run `markdown_to_respec` when a file is modified?

**Comment by edsu** [comment]
@Shrinks99 ok, you should be able to `pip install markdown-to-respec` and then run it by pointing it to a directory where there are markdown files. By default it won't publish the results to Github unless you tell it to. 

```
$ markdown-to-respec wacz-ipfs
converted wacz-ipfs/latest/index.md to wacz-ipfs/latest/index.html
```

**Pull request merged**
